const data = {
    products:[
        {
            _id: '1',
            name: 'Owl Pandant/Necklace',
            category: 'Necklace',
            image: '/images/p1.jpg',
            price: '180tk',
            countInStock: 21,
            brand: 'Aliexpress',
            rating: 4.5,
            numReviews: 12,
            descripton: 'Beautiful and heavy metal made product',
        },
        {
            _id: '2',
            name: 'Crown Shape Ring',
            category: 'Ring',
            image: '/images/p2.jpg',
            price: '80tk',
            countInStock: 17,
            brand: 'Aliexpress',
            rating: 4.6,
            numReviews: 15,
            descripton: 'Beautiful and heavy metal made product',
        },
        {
            _id: '3',
            name: 'Antique Pocket Watch',
            category: 'Watch',
            image: '/images/p3.jpg',
            price: '300tk',
            countInStock: 9,
            brand: 'Aliexpress',
            rating: 4.4,
            numReviews: 16,
            descripton: 'Beautiful and heavy metal made product',
        },
        {
            _id: '4',
            name: 'Pandent Earring',
            category: 'Earrings',
            image: '/images/p4.jpg',
            price: '140tk',
            countInStock: 52,
            brand: 'Aliexpress',
            rating: 4.7,
            numReviews: 38,
            descripton: 'Beautiful and heavy metal made product',
        },
        {
            _id: '5',
            name: 'Vintage Hand Band',
            category: 'Band',
            image: '/images/p5.jpg',
            price: '70tk',
            countInStock: 25,
            brand: 'Aliexpress',
            rating: 4.3,
            numReviews: 21,
            descripton: 'Beautiful and heavy metal made product',
        },
        {
            _id: '6',
            name: 'Single Wing Pandent/Necklace',
            category: 'Necklace',
            image: '/images/p6.jpg',
            price: '150tk',
            countInStock: 8,
            brand: 'Aliexpress',
            rating: 3.9,
            numReviews: 14,
            descripton: 'Beautiful and heavy metal made product',
        },
        {
            _id: '7',
            name: 'Crystal Solid Ring Set',
            category: 'Ring',
            image: '/images/p7.jpg',
            price: '400tk',
            countInStock: 15,
            brand: 'Aliexpress',
            rating: 4.5,
            numReviews: 19,
            descripton: 'Beautiful and heavy metal made product',
        },
        {
            _id: '8',
            name: 'Multiple Ring Set',
            category: 'Ring',
            image: '/images/p8.jpg',
            price: '150tk',
            countInStock: 1,
            brand: 'Aliexpress',
            rating: 4.3,
            numReviews: 16,
            descripton: 'Beautiful and heavy metal made product',
        },
        {
            _id: '9',
            name: 'White Crytal Earring Set',
            category: 'Earring',
            image: '/images/p9.jpg',
            price: '370tk',
            countInStock: 2,
            brand: 'Aliexpress',
            rating: 4.2,
            numReviews: 12,
            descripton: 'Beautiful and heavy metal made product',
        },
        {
            _id: '10',
            name: 'Crystal & Round Necklace',
            category: 'Necklace',
            image: '/images/p10.jpg',
            price: '320tk',
            countInStock: 0,
            brand: 'Aliexpress',
            rating: 3.9,
            numReviews: 7,
            descripton: 'Beautiful and heavy metal made product',
        },
    ],
};
export default data;